name: Preview or update Pulumi app artur-test-org/static-site/dev
on:
  push:
    branches:
      - main
    paths:
      - '**/*'
  pull_request:
    branches:
      - main
    paths:
      - '**/*'

# These are the environment variables that jobs in the workflow have access to.
# By defining them here, all jobs/steps will have access to these variables.
env:
# AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
# AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}  # Optional
# AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_BACKEND_URL: https://api-simon-dev.review-stacks.pulumi-dev.io
  PULUMI_STACK_NAME: artur-test-org/static-site/dev
  PULUMI_WORKING_DIRECTORY: .

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    steps:

      # Turnstyle is used to prevent multiple push jobs from running at the same time. We
      # limit it to push jobs to allow PR jobs to run concurrently.
      - name: Turnstyle
        if: ${{ github.event_name == 'push' }}
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - run: npm ci
        working-directory: ${{ env.PULUMI_WORKING_DIRECTORY }}

      - name: PR previews
        if: ${{ github.event_name == 'pull_request' }}
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}

      - name: Apply infrastructure update
        if: ${{ github.event_name == 'push' }}
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}


      # If you'd like to run your Pulumi application outside of the official GitHub Action

      #- name: Install Pulumi CLI
      #  uses: pulumi/setup-pulumi@v2

      #- name: PR previews
      #  run: pulumi preview -s $PULUMI_STACK_NAME --cwd $PULUMI_WORKING_DIRECTORY
      #  if: ${{ github.event_name == 'pull_request' }}

      #- name: Apply infrastructure update
      #  run: pulumi update --yes -s $PULUMI_STACK_NAME --cwd $PULUMI_WORKING_DIRECTORY
      #  if: ${{ github.event_name == 'push' }}
